name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "412c1514796cf3fb36c9c2774bb748e5ded14e95e41a15125bf72d64ca1b49c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
