name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32b5c941f72566a72deb64aa22a04383fa370ad604989b2bbd5477dd0e801efd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
