name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf7eb70026275cb2f3d6d7993e923e1a43828785c75cbba693fea37abae2d900"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
