name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0970299551a1932fde42e754e7df775250672b5c199844c3a4aa910790103c5d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
