name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b12bf8592b233817dce3d5dc7ab5db3badbb3a77ef59721b076adcfbe1c4db70"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
