name = "Hasencraft"
author = "Hasencraft Team"
version = "0.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f164883a7cd562ecb4599f41ce30ee240ca3fa64437869b49e1b7613535c8eb9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.247"
